# Generated by Django 4.1.3 on 2023-05-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accredit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
