# Generated by Django 4.1.3 on 2023-05-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accredit', '0003_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(default=None, verbose_name='登录时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='u_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态 0:关闭 1:正常 2:异常'),
        ),
    ]
