# Generated by Django 4.1.3 on 2023-05-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accredit', '0004_user_login_time_user_u_time_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
