# Generated by Django 4.1.3 on 2023-05-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accredit', '0005_alter_user_c_time_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='123', max_length=250),
        ),
    ]
