# Generated by Django 4.1.3 on 2023-04-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync', '0003_alter_datafactoryintranetconfig_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafactoryintranetconfig',
            name='password',
            field=models.CharField(default=None, max_length=125),
        ),
        migrations.AddField(
            model_name='datafactoryintranetconfig',
            name='user',
            field=models.CharField(default=None, max_length=125),
        ),
        migrations.AlterField(
            model_name='datafactoryintranetconfig',
            name='host',
            field=models.GenericIPAddressField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='datafactoryintranetconfig',
            name='name',
            field=models.CharField(default=None, max_length=125, unique=True),
        ),
    ]
